### ISSUE TITLE
MC 1.12.2 - Forge 1.12.2-14.23.4.2705 - DaFlight 5.2.2-mc1.12.2 - Error on load

### ISSUE THREAD

**Issue by phlnx** [DaFlight/DaFlight#22]
Apologies if this is a trivial error to fix.

I have used DaFlight on MC 1.12 successfully.

```
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:113)
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:106)
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:77)
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.dags.daflight.launch.DaFlightTweaker.injectIntoClassLoader(DaFlightTweaker.java:42)
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:49:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by dags-** [comment]
Not familiar with that error, could you post the whole log?

**Comment by phlnx** [comment]
Yes. Apologies for the late reply, I could not fulfill your request at work. Please see the full content of debug.log here: https://pastebin.com/eqb8UfGB

I tried launching without DaFlight 5.2.2-mc1.12.2 and it worked perfectly.

**Comment by dags-** [comment]
Struggling to think what might be the issue on DaFlight's side of things.

I'm thinking either:
- one of the other mods may be shipping an incompatible version of the Mixins library
- one of the other mods' core plugin is doing something that is tripping up the Mixins library that DaFlight relies on

One (slightly tedious) way of narrowing down the true cause would be to start with just forge and DF and see if it launches, then add in the other mods one by one and see which breaks it.

I couldn't find the source or jar for the xray mod you're using, so maybe try take that one out first?

**Comment by dags-** [comment]
Another possibility could be that newer versions of forge don't work with the version Mixin that DaFlight's using

**Comment by phlnx** [comment]
Hello, thank you for your reply. I removed all of the mods, leaving only daflight 5.2.2. 

No change, it still crashes.

The debug.log ends with pretty much the same lines,
```
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:113)
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:106)
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:77)
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.dags.daflight.launch.DaFlightTweaker.injectIntoClassLoader(DaFlightTweaker.java:42)
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:33:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

The only thing left for me to do is move to the newest version of Forge. I could do that, unless you think it would make no difference.

Thank you for your assistance! I hope we can get this sorted. I have become accustomed to your mod in my long months of 1.12 :-)

**Comment by AeSix** [comment]
try a release from before August. Work your way newer so you can tell dags which forge its first broken on.

**Comment by phlnx** [comment]
The version of Forge I am currently using, as stated, is 14.23.4.2705. It was released on May 27th, 2018, so well before August - I am assuming you were referring to August 2018.

**Comment by AeSix** [comment]
I'm using 14.23.4.2747. 
I was thinking you were using a much more recent version.

**Comment by AeSix** [comment]
(and it works perfectly well, with liteloader and optifine as well)

**Comment by phlnx** [comment]
I am using the "recommended" version.

**Comment by phlnx** [comment]
Ok, I installed the newest version of Forge (14.23.4.2759), and it crashes as usual. So I installed also the version you suggest (14.23.4.2747), and it also crashes as usual. Both times with DaFlight being the only mod in the folder. Removing DaFlight, MineCraft starts.

I also tried using a newer version of Java (I was using last year's), but apparently it did not change anything.

Full debug.log for 14.23.4.2747 follows.

Thank you for any help you can give.


```
[18:56:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:56:41] [main/DEBUG] [FML]: Injecting tracing printstreams for STDOUT/STDERR.
[18:56:41] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2747 for Minecraft 1.12.2 loading
[18:56:41] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_181
[18:56:41] [main/DEBUG] [FML]: Java classpath at launch is:
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.12.2-14.23.4.2747\forge-1.12.2-14.23.4.2747.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar
[18:56:41] [main/DEBUG] [FML]: Java library path at launch is:
[18:56:41] [main/DEBUG] [FML]:     C:\Users\USER_NAME\AppData\Local\Temp\d223-68d0-0c79-5776
[18:56:41] [main/DEBUG] [FML]: Determined Minecraft Libraries Root: C:\Users\USER_NAME\AppData\Roaming\.minecraft\libraries
[18:56:41] [main/DEBUG] [FML]: Cleaning up mods folder: C:\Users\USER_NAME\AppData\Roaming\.minecraft\mods
[18:56:41] [main/DEBUG] [FML]: Examining file: daflight-5.2.2-mc1.12.2.jar
[18:56:41] [main/DEBUG] [FML]: Enabling runtime deobfuscation
[18:56:41] [main/DEBUG] [FML]: Instantiating coremod class FMLCorePlugin
[18:56:41] [main/DEBUG] [FML]: Found signing certificates for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin)
[18:56:41] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[18:56:41] [main/DEBUG] [FML]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[18:56:41] [main/DEBUG] [FML]: Enqueued coremod FMLCorePlugin
[18:56:41] [main/DEBUG] [FML]: Instantiating coremod class FMLForgePlugin
[18:56:41] [main/DEBUG] [FML]: Found signing certificates for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin)
[18:56:41] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[18:56:41] [main/DEBUG] [FML]: Enqueued coremod FMLForgePlugin
[18:56:41] [main/DEBUG] [FML]: All fundamental core mods are successfully located
[18:56:41] [main/DEBUG] [FML]: Discovering coremods
[18:56:41] [main/INFO] [FML]: Searching C:\Users\USER_NAME\AppData\Roaming\.minecraft\mods for mods
[18:56:41] [main/DEBUG] [FML]:   Adding daflight-5.2.2-mc1.12.2.jar to the mod list
[18:56:41] [main/DEBUG] [FML]: Examining for coremod candidacy daflight-5.2.2-mc1.12.2.jar
[18:56:41] [main/INFO] [FML]: Loading tweaker me.dags.daflight.launch.DaFlightLoaderTweaker from daflight-5.2.2-mc1.12.2.jar
[18:56:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Loading tweak class name me.dags.daflight.launch.DaFlightLoaderTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:56:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:56:41] [main/DEBUG] [FML]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[18:56:41] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[18:56:41] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[18:56:41] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[18:56:41] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[18:56:41] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[18:56:41] [main/DEBUG] [FML]: Injection complete
[18:56:41] [main/DEBUG] [FML]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[18:56:41] [main/DEBUG] [FML]: Running coremod plugin FMLCorePlugin
[18:56:42] [main/DEBUG] [FML]: Read 1097 binary patches
[18:56:42] [main/DEBUG] [FML]: Loading deobfuscation resource /deobfuscation_data-1.12.2.lzma with 36083 records
[18:56:43] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:56:43] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:56:43] [main/DEBUG] [FML]: Coremod plugin class FMLCorePlugin run successfully
[18:56:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:56:43] [main/DEBUG] [FML]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[18:56:43] [main/DEBUG] [FML]: Injection complete
[18:56:43] [main/DEBUG] [FML]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[18:56:43] [main/DEBUG] [FML]: Running coremod plugin FMLForgePlugin
[18:56:43] [main/DEBUG] [FML]: Coremod plugin class FMLForgePlugin run successfully
[18:56:43] [main/INFO] [LaunchWrapper]: Calling tweak class me.dags.daflight.launch.DaFlightLoaderTweaker
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:113)
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:106)
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:77)
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at me.dags.daflight.launch.DaFlightTweaker.injectIntoClassLoader(DaFlightTweaker.java:42)
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:56:43] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by AeSix** [comment]
Yeah... there should be a newer recommended one by now. But use what works - a lot of times, the forge devs will fix an issue for mod devs, and theur mod simply won't work on previous versions (with exceptions). 

I use .2747 daily with no issues. 

try 2707, 2712, 2724, 2729... or 2747 since it's known to work properly.

These numbers come from educated guesses from looking at the forge changelog.

**Comment by phlnx** [comment]
No, the recommended version is still .2705. I'm OK in using another of course, but so far I have used four and none of them seems to work. :-(

**Comment by AeSix** [comment]
same version of java as me. same daflight version as me... even tried same forge as me.

The only difference is I'm not using sponge. 

I feel like it;s trying to load as a Sponge mod instead of a Forge mod. 

Can you move the df jar into (or out of) the mods/1.12.2/ folder? See if that affects anything?

**Comment by phlnx** [comment]
I'm really baffled because I seriously have no idea what Sponge even is. How can I tell if I have it installed? I don't remember even running into that.

The jar file is not in mods/1.12.2 but in mods/ straight away. I've never used a versioned mod folder in my life :-)

**Comment by AeSix** [comment]
yeah, it needs to be in mods/1.12.2/ - dags' instructions right on the main project page. Forge looks in the different than the mods/ folder. 

try and see if that was your issue :)

**Comment by phlnx** [comment]
Weird. I never put any mods in a versioned subfolder, ever.

Even DaFlight itself for 1.12 was in mods/.

I never had such an issue before with any mod. I've been playing since 1.7.4. Forge always found all the mods I have ever chosen :-)

I just tried following your suggestion, but it ended exactly as before - crashed at launch with the same few lines closing debug.log.

**Comment by AeSix** [comment]
I...
the only suggestion i have left is to remove all current Minecraft/Forge/mods etc, freshly download forge and df, and do a clean-slate install.

Test on another computer if you can.
it *should* be working.  

If you're having issues w/ other things on the PC, run memtest86+, just in case.  </ideas>

**Comment by phlnx** [comment]
No other issues on my PC. It's been steadily working for six years now. Minecraft works perfectly if I do not include DaFlight, even with all my other mods - or a subset of them. I have installed several versions of Forge today, and tried them all. I do not have another computer to test now.

DaFlight worked flawlessly for me on 1.12. I moved to 1.12.2 two days ago and managed to find an updated version of all of my previous mods, and they all work, except DaFlight.

One thing you might help me with is that mention of Sponge which is still unclear for me. Browsing through DaFlight's code I can see org.spongepowered.asm.mixin.Mixin mentioned in /src/main/java/me/dags/daflight/mixin/MixinMinecraft.java. So it looks like sponge is carried by DaFlight and not something I might have installed somewhere (as I initially feared).

Just as a hunch, would you share your JVM options?

**Comment by AeSix** [comment]
So, I just looked. 

I'm using Java 1.8.0_161, I was mistaken earlier.  You're using 181. Maybe the difference? :S
But here's my args:
-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M

( I believe this is defaults)

**Comment by phlnx** [comment]
I was using 1.8.0_151 earlier.

My Arguments were:

`-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M`

(and of course I have no idea when or where I found those).

I tried yours but as expected it didn't make a difference. Same error.

I really don't know what else to do...

**Comment by dags-** [comment]
The Sponge platform is primarily a server-side software for loading/managing plugins (like bukkit/spigot). The Sponge developers created a tool called [Mixins](https://github.com/SpongePowered/Mixin) in order to make their code simpler, safer, and easier to write.

Mixins is incredibly useful as a general modding tool, so DaFlight uses it. The DaFlight mod jar includes a specific version of the Mixin library in order to work.

It's sounding like something has changed with newer versions of Forge that is causing the Mixin library not to function correctly, meaning in turn that DaFlight cannot do the modifications it needs to in order to load (ie it crashes).


It's something I'll try look into this weekend if I have time. It might be as simple as updating the version of Mixins that DaFlight comes with

**Comment by phlnx** [comment]
@dags- , thank you. I appreciate your interest in the matter although @AeSix apparently manages to make DaFlight work with 1.12.2 and Forge, so I'm at a loss at what could really be happening. Please let me know if there is anything more I can do. Should I try installing liteloader? I don't think I have ever used it and I am actually unfamiliar with it but I would try that if you think it could help.

**Comment by dags-** [comment]
@phlnx it does absolutely work with some versions of Forge on 1.12.2, for example I know forge build `14.23.3.2655` works with daflight because there is a server modpack using this specific version and about 50 odd users having no problem.

Again, what I'm saying is that I suspect newer versions of forge do not work for whatever reason. The log you posted you were using forge build `14.23.4.2705`

**Comment by phlnx** [comment]
@dags- got it, thanks. Waiting for further development. I will be out tonight and tomorrow but I should be back tomorrow night in case you need testing. I live in the CEST time zone.

**Comment by dags-** [comment]
I think I know what the issue is now, though not fully why the mod works for some and not others... maybe the inclusion of certain other mixin mods actually fixes the problem with DF 😅

@phlnx would you mind testing the following:
https://github.com/DaFlight/DaFlight/releases/tag/1.12.2-5.2.2-TEST-0

**Comment by phlnx** [comment]
@dags- , thank you for taking care of this. I can confirm that it works on a 1.12.2 installation with all my other mods and with Forge version 14.23.4.2705. Great job! This issue can be closed.

**Comment by dags-** [comment]
Thanks for confirming! I'll leave open for now as a self-reminder to push the fix to the master branch

**Comment by T0T4R4** [comment]
I confirm it works with those versions as well @phlnx @dags-
